apiVersion: v1
kind: Service
metadata:
  name: hw06-service
  labels:
    app: hw06
spec:
  type: NodePort
  selector:
    app: hw06
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      name: web