{
 "title": "hw06 service",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "service", "query": "hw06-service" },
   { "name": "measurePeriod", "query": "20s,1m,10m,30m,1h" },
   {
    "name": "namespace",
    "query": {
     "query": "label_values(go_goroutines{service=\"$service\"}, namespace)"
    }
   },
   { "name": "pods", "query": "hw06-deployment-.*" }
  ]
 },
 "panels": [
  { "title": "Service", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Latency",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "dtdurations" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum by (le) (rate(request_duration_histogram_seconds_bucket{service=\"$service\",namespace=\"$namespace\"}[$measurePeriod])))",
     "legendFormat": "95 quantile"
    },
    {
     "expr": "histogram_quantile(0.99, sum by (le) (rate(request_duration_histogram_seconds_bucket{service=\"$service\",namespace=\"$namespace\"}[$measurePeriod])))",
     "legendFormat": "99 quantile"
    },
    {
     "expr": "histogram_quantile(1.0, sum by (le) (rate(request_duration_histogram_seconds_bucket{service=\"$service\",namespace=\"$namespace\"}[$measurePeriod])))",
     "legendFormat": "max"
    },
    {
     "expr": "histogram_quantile(0.5, sum by (le) (rate(request_duration_histogram_seconds_bucket{service=\"$service\",namespace=\"$namespace\"}[$measurePeriod])))",
     "legendFormat": "50 quantile"
    }
   ]
  },
  {
   "title": "RPC (requests per second)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 1 },
   "targets": [
    {
     "expr": "sum by (method)(rate(request_duration_histogram_seconds_count{service=\"$service\",namespace=\"$namespace\"}[$measurePeriod]))",
     "legendFormat": "{{method}}"
    }
   ]
  },
  {
   "title": "Error rate (Error count per $measurePeriod)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 1 },
   "targets": [
    {
     "expr": "sum by (method, status_code)(increase(request_duration_histogram_seconds_count{service=\"$service\",namespace=\"$namespace\",status_code!=\"200\"}[$measurePeriod]))",
     "legendFormat": "{{method}} {{status_code}}"
    }
   ]
  },
  { "title": "Ingress", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 } },
  {
   "title": "Latency",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "dtdurations" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum by (le) (rate(nginx_ingress_controller_request_duration_seconds_bucket{exported_service=\"$service\",namespace=\"$namespace\"}[$measurePeriod])))",
     "legendFormat": "95 quantile"
    },
    {
     "expr": "histogram_quantile(0.99, sum by (le) (rate(nginx_ingress_controller_request_duration_seconds_bucket{exported_service=\"$service\",namespace=\"$namespace\"}[$measurePeriod])))",
     "legendFormat": "99 quantile"
    },
    {
     "expr": "histogram_quantile(1.0, sum by (le) (rate(nginx_ingress_controller_request_duration_seconds_bucket{exported_service=\"$service\",namespace=\"$namespace\"}[$measurePeriod])))",
     "legendFormat": "max"
    },
    {
     "expr": "histogram_quantile(0.5, sum by (le) (rate(nginx_ingress_controller_request_duration_seconds_bucket{exported_service=\"$service\",namespace=\"$namespace\"}[$measurePeriod])))",
     "legendFormat": "50 quantile"
    }
   ]
  },
  {
   "title": "RPC (requests per second)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 11 },
   "targets": [
    {
     "expr": "sum by (method)(rate(nginx_ingress_controller_request_duration_seconds_count{exported_service=\"$service\",namespace=\"$namespace\"}[$measurePeriod]))",
     "legendFormat": "{{method}}"
    }
   ]
  },
  {
   "title": "Error rate (Error count per $measurePeriod)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 11 },
   "targets": [
    {
     "expr": "sum by (method, status)(increase(nginx_ingress_controller_request_duration_seconds_count{exported_service=\"$service\",namespace=\"$namespace\",status!=\"200\"}[$measurePeriod]))",
     "legendFormat": "{{method}} {{status}}"
    }
   ]
  },
  { "title": "Resources", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 } },
  {
   "title": "CPU",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 21 },
   "targets": [
    {
     "expr": "sum(node_namespace_pod_container:container_cpu_usage_seconds_total:sum_irate{namespace=\"monitoring\",pod=~\"$pods\"}) by (pod)",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(node_namespace_pod_container:container_memory_working_set_bytes{namespace=\"monitoring\",pod=~\"$pods\"}) by (pod)",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  { "title": "Alerts", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 30 } },
  {
   "title": "Error rate (Error count per $measurePeriod) $service",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 31 },
   "targets": [
    {
     "expr": "sum by (method, status_code)(increase(request_duration_histogram_seconds_count{service=\"hw06-service\",namespace=\"monitoring\",status_code=\"500\"}[10s]))",
     "legendFormat": "{{method}} {{status_code}}"
    }
   ]
  }
 ]
}